### ISSUE TITLE
Output filename/location

### ISSUE THREAD

**Issue by MegaSp00n** [UKSquire/BBCiPlayer#2]
I monitor a variety of series with a regular schedule to update new episodes and download.

As this tool overwrites the file each time (by design, I understand), I can't run multiple series downloads at the same time, instead waiting for one download to finish before creating a new bbc.txt with the next series.

If the output filename and location could be specified, this allows multiple instances to run. Changing of the filepath also allows the file to be saved in custom locations to get around permission pains.

Awesome tool.

**Comment by UKSquire** [comment]
Hi MegaSp00n - I hadn't realised there was much use of the tool, to be honest, so sorry for the delay.

Let me see what I can do to implement your suggested changes, and I'll get back to you as soon as I can.

**Comment by UKSquire** [comment]
@MegaSp00n - I've added a second command line param for now. Example use:

BBC-Iplayer.exe https://www.bbc.co.uk/iplayer/episodes/m0009tgy/bing?seriesId=m0009xhl myfile.txt

You should also be able to specify other locations e.g. g:\films\myfile.txt
